
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN DIVIDE ID INT LPAREN MINUS NUMBER PLUS RPAREN SEMI TIMESprogram : statementsstatements : statements statementstatements : statementstatement : INT ID SEMIstatement : ID ASSIGN expression SEMIexpression : expression PLUS expression\n                  | expression MINUS expression\n                  | expression TIMES expression\n                  | expression DIVIDE expressionexpression : LPAREN expression RPARENexpression : NUMBERexpression : ID'
    
_lr_action_items = {'INT':([0,2,3,6,9,14,],[4,4,-3,-2,-4,-5,]),'ID':([0,2,3,4,6,8,9,12,14,15,16,17,18,],[5,5,-3,7,-2,10,-4,10,-5,10,10,10,10,]),'$end':([1,2,3,6,9,14,],[0,-1,-3,-2,-4,-5,]),'ASSIGN':([5,],[8,]),'SEMI':([7,10,11,13,20,21,22,23,24,],[9,-12,14,-11,-6,-7,-8,-9,-10,]),'LPAREN':([8,12,15,16,17,18,],[12,12,12,12,12,12,]),'NUMBER':([8,12,15,16,17,18,],[13,13,13,13,13,13,]),'PLUS':([10,11,13,19,20,21,22,23,24,],[-12,15,-11,15,15,15,15,15,-10,]),'MINUS':([10,11,13,19,20,21,22,23,24,],[-12,16,-11,16,16,16,16,16,-10,]),'TIMES':([10,11,13,19,20,21,22,23,24,],[-12,17,-11,17,17,17,17,17,-10,]),'DIVIDE':([10,11,13,19,20,21,22,23,24,],[-12,18,-11,18,18,18,18,18,-10,]),'RPAREN':([10,13,19,20,21,22,23,24,],[-12,-11,24,-6,-7,-8,-9,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statements':([0,],[2,]),'statement':([0,2,],[3,6,]),'expression':([8,12,15,16,17,18,],[11,19,20,21,22,23,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statements','program',1,'p_program','Analizador_Semantico.py',111),
  ('statements -> statements statement','statements',2,'p_statements_multiple','Analizador_Semantico.py',116),
  ('statements -> statement','statements',1,'p_statements_single','Analizador_Semantico.py',121),
  ('statement -> INT ID SEMI','statement',3,'p_statement_declaration','Analizador_Semantico.py',126),
  ('statement -> ID ASSIGN expression SEMI','statement',4,'p_statement_assignment','Analizador_Semantico.py',131),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','Analizador_Semantico.py',136),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop','Analizador_Semantico.py',137),
  ('expression -> expression TIMES expression','expression',3,'p_expression_binop','Analizador_Semantico.py',138),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_binop','Analizador_Semantico.py',139),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_paren','Analizador_Semantico.py',144),
  ('expression -> NUMBER','expression',1,'p_expression_number','Analizador_Semantico.py',149),
  ('expression -> ID','expression',1,'p_expression_var','Analizador_Semantico.py',154),
]
